### ISSUE TITLE
Error when building mini-fs 

### ISSUE THREAD

**Issue by bianliangpai** [dontpanic92/OpenPAL3#11]
I'm trying to run this project as the README.md said, however there is an error when building mini-fs. 

> Compiling mini-fs v0.2.2 (https://github.com/dontpanic92/mini-fs/#931b4f9b)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> C:\Users\{Username}\.cargo\git\checkouts\mini-fs-4975b622e5d2fed3\931b4f9\src\lib.rs:50:1
   |
50 | #![feature(osstring_ascii)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error

Maybe I'm not at the corrent git branch, or there still are some other operations to do before building ?
Very glad to receive your reply.

**Comment by dontpanic92** [comment]
For now the `nightly` toolchain is needed as we use several non-stable features in rust. Specially, due to an issue from an upstream library, we have to stick on nightly 2021-03-24.

So please install a nightly-03-24 toolchain (e.g. `nightly-2021-03-24-x86_64-pc-windows-msvc`) and try compiling again.

**Comment by bianliangpai** [comment]
This works, thank you.
